CREATE TABLE IF NOT EXISTS ACCOUNTS
(
  ID INTEGER PRIMARY KEY NOT NULL,
  CUSTOMER_ID INTEGER NOT NULL,
  ACC_INFO_ID INTEGER NOT NULL,
  REGISTER_DATE TIMESTAMP NOT NULL,
  LAST_LOGIN_DATE TIMESTAMP,
  ACC_NUMBER INTEGER NOT NULL,
  CONSTRAINT ACCOUNTS_CUSTOMERS_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID),
  CONSTRAINT ACCOUNTS_ACCOUNT_INFO_ID_FK FOREIGN KEY (ACC_INFO_ID) REFERENCES ACCOUNT_INFO (ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS ACCOUNTS_ACC_NUMBER_UINDEX ON ACCOUNTS (ACC_NUMBER);
CREATE TABLE IF NOT EXISTS ACCOUNT_INFO
(
  ID INTEGER PRIMARY KEY NOT NULL,
  BALANCE DECIMAL(18) DEFAULT 0 NOT NULL,
  CURRENCY_ID INTEGER NOT NULL,
  CONSTRAINT ACCOUNT_INFO_CURRENCIES_ID_FK FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCIES (ID)
);
CREATE TABLE IF NOT EXISTS CARDS
(
  ID INTEGER PRIMARY KEY NOT NULL,
  NUMBER VARCHAR(16) NOT NULL,
  CARD_TYPE INTEGER NOT NULL,
  EXPIRATION_DATE TIMESTAMP NOT NULL,
  SECURE_CODE VARCHAR(255) NOT NULL,
  IS_BLOCK BOOLEAN DEFAULT 0 NOT NULL,
  ACCOUNT_ID INTEGER NOT NULL,
  CONSTRAINT CARDS_ACCOUNTS_ID_FK FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS CARDS_NUMBER_UINDEX ON CARDS (NUMBER);
CREATE TABLE IF NOT EXISTS CARD_TYPES
(
  ID INTEGER PRIMARY KEY NOT NULL,
  TYPE_NAME VARCHAR(255),
  LOAN_ID INTEGER,
  CONSTRAINT CARD_TYPES_LOANS_ID_FK FOREIGN KEY (LOAN_ID) REFERENCES LOANS (ID)
);
CREATE TABLE IF NOT EXISTS CURRENCIES
(
  ID INTEGER PRIMARY KEY NOT NULL,
  CURRENCY_NAME VARCHAR(2147483647) NOT NULL
);
CREATE TABLE IF NOT EXISTS CUSTOMERS
(
  ID INTEGER PRIMARY KEY NOT NULL,
  FIRST_NAME VARCHAR(2147483647) NOT NULL,
  LAST_NAME VARCHAR(2147483647) NOT NULL,
  MIDDLE_NAME VARCHAR(2147483647),
  EMAIL VARCHAR(2147483647) NOT NULL,
  PHONE_NUMBER VARCHAR(2147483647) NOT NULL,
  PASSWORD VARCHAR(2147483647) NOT NULL
);
CREATE TABLE IF NOT EXISTS CUSTOMERS_ROLES
(
  ID INTEGER NOT NULL,
  CUSTOMER_ID INTEGER NOT NULL,
  ROLE_ID INTEGER NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS CUSTOMERS_ROLES_ID_UINDEX ON CUSTOMERS_ROLES (ID);
CREATE TABLE IF NOT EXISTS LOANS
(
  ID INTEGER PRIMARY KEY NOT NULL,
  AMOUNT DECIMAL(18) NOT NULL,
  PAID DECIMAL(18),
  LOAN_DATE TIMESTAMP NOT NULL,
  ANNUAL_INTEREST DOUBLE NOT NULL,
  LOAN_EXPIRATION_DATE TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS ROLES
(
  ID INTEGER PRIMARY KEY NOT NULL,
  ROLE_NAME VARCHAR(2147483647) NOT NULL
);